#! /bin/bash

if [[ $# < 2 ]]; then
    echo
    echo "usage: ./validate-prp [costed] <domain> <problem> [--keep-files]"
    echo
    exit 1
fi

MODE=""
if [[ "$1" == "costed" ]]; then
    MODE="costed"
    shift
fi
ROOT=$(dirname "$0")
echo $ROOT

${ROOT}/prp $MODE $1 $2 --dump-policy 2 --optimize-final-policy 1 --detect-deadends 1 --jic-limit 90 --planlocal 1 --partial-planlocal 1 --limit-planlocal 1 --plan-with-policy 1 --depth 1000 --generalize-deadends 1 --online-deadends 1 --optimized-scd 1 --debug-output 1 --trials 1000

#${ROOT}/prp $MODE $1 $2 --dump-policy 2 --optimize-final-policy 1 --jic-limit 30 --plan-with-policy 0

python ${ROOT}/../prp-scripts/translate_policy.py > human_policy.out


if [[ "$MODE" == "costed" ]]
then
  DFN="_cost_stripped_domain.pddl"
  PFN="_cost_stripped_problem.pddl"
  python ${ROOT}/../prp-scripts/metric_stripper.py $1 $2 $DFN $PFN
else
  DFN=$1
  PFN=$2
fi

python ${ROOT}/../prp-scripts/validator.py $DFN $PFN human_policy.out prp

dot -Tpng graph.dot > graph.png

if [ "--keep-files" != "$3" ]; then
  ${ROOT}/cleanup
  rm -f policy.out
  rm -f human_policy.out
  rm -f graph.dot
  rm -f action.map
  rm -f graph.png
  rm -f unhandled.states
  rm -f _cost_stripped_domain.pddl
  rm -f _cost_stripped_problem.pddl
fi
